# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 057a780364882857ee3017162abc89b3bd966e01b5f490663fbbee1014260e1c3d7ecb6705972021992d6f861c7f27cf91f0a0a6b9141b537f45d5ea38c72cfa

test:
  secret_key_base: f4e4a0aaa6eb755b7ceaa96b6552eb7f0a94f7563c12bd12a0f88e0bdd1315836c7cef3c4168c0cfc0333ff675c69e6d4dd8f2d1cbdc24c9cee0c6ed9098e8a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
